2023-02-16 13:05:20,482 INFO    StreamThr :21960 [internal.py:wandb_internal():87] W&B internal server running at pid: 21960, started at: 2023-02-16 13:05:20.481786
2023-02-16 13:05:20,485 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status
2023-02-16 13:05:20,510 INFO    WriterThread:21960 [datastore.py:open_for_write():85] open: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/run-zr31z4za.wandb
2023-02-16 13:05:20,511 DEBUG   SenderThread:21960 [sender.py:send():334] send: header
2023-02-16 13:05:20,514 DEBUG   SenderThread:21960 [sender.py:send():334] send: run
2023-02-16 13:05:21,006 INFO    SenderThread:21960 [dir_watcher.py:__init__():216] watching files in: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files
2023-02-16 13:05:21,006 INFO    SenderThread:21960 [sender.py:_start_run_threads():1065] run started: zr31z4za with start time 1676563520.482718
2023-02-16 13:05:21,006 DEBUG   SenderThread:21960 [sender.py:send_request():361] send_request: summary_record
2023-02-16 13:05:21,006 INFO    SenderThread:21960 [sender.py:_save_file():1319] saving file wandb-summary.json with policy end
2023-02-16 13:05:21,007 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: check_version
2023-02-16 13:05:21,007 DEBUG   SenderThread:21960 [sender.py:send_request():361] send_request: check_version
2023-02-16 13:05:21,088 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: run_start
2023-02-16 13:05:21,090 DEBUG   HandlerThread:21960 [system_info.py:__init__():31] System info init
2023-02-16 13:05:21,090 DEBUG   HandlerThread:21960 [system_info.py:__init__():46] System info init done
2023-02-16 13:05:21,090 INFO    HandlerThread:21960 [system_monitor.py:start():151] Starting system monitor
2023-02-16 13:05:21,091 INFO    SystemMonitor:21960 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-02-16 13:05:21,091 INFO    HandlerThread:21960 [system_monitor.py:probe():172] Collecting system info
2023-02-16 13:05:21,093 INFO    SystemMonitor:21960 [interfaces.py:start():168] Started cpu
2023-02-16 13:05:21,094 INFO    SystemMonitor:21960 [interfaces.py:start():168] Started disk
2023-02-16 13:05:21,095 INFO    SystemMonitor:21960 [interfaces.py:start():168] Started gpu
2023-02-16 13:05:21,096 INFO    SystemMonitor:21960 [interfaces.py:start():168] Started memory
2023-02-16 13:05:21,098 INFO    SystemMonitor:21960 [interfaces.py:start():168] Started network
2023-02-16 13:05:21,132 DEBUG   HandlerThread:21960 [system_info.py:probe():195] Probing system
2023-02-16 13:05:21,133 DEBUG   HandlerThread:21960 [git.py:repo():40] git repository is invalid
2023-02-16 13:05:21,133 DEBUG   HandlerThread:21960 [system_info.py:probe():241] Probing system done
2023-02-16 13:05:21,133 DEBUG   HandlerThread:21960 [system_monitor.py:probe():181] {'os': 'Linux-4.15.0-197-generic-x86_64-with-glibc2.27', 'python': '3.10.8', 'heartbeatAt': '2023-02-16T16:05:21.132335', 'startedAt': '2023-02-16T16:05:20.380878', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': 'IC/knowledge-distillation_antigo.ipynb', 'root': '/home/luigi-doria', 'host': 'ml', 'username': 'luigi-doria', 'executable': '/home/luigi-doria/miniconda3/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 0.7999999999999999, 'min': 800.0, 'max': 4500.0}, 'cpu_freq_per_core': [{'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}, {'current': 0.8, 'min': 800.0, 'max': 4500.0}], 'disk': {'total': 915.3223114013672, 'used': 345.3266410827637}, 'gpu': 'NVIDIA GeForce GTX 1060 6GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1060 6GB', 'memory_total': 6371475456}], 'memory': {'total': 7.717708587646484}}
2023-02-16 13:05:21,133 INFO    HandlerThread:21960 [system_monitor.py:probe():182] Finished collecting system info
2023-02-16 13:05:21,133 INFO    HandlerThread:21960 [system_monitor.py:probe():185] Publishing system info
2023-02-16 13:05:21,133 DEBUG   HandlerThread:21960 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-02-16 13:05:21,134 DEBUG   HandlerThread:21960 [system_info.py:_save_pip():67] Saving pip packages done
2023-02-16 13:05:21,134 DEBUG   HandlerThread:21960 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-02-16 13:05:22,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_created():275] file/dir created: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/wandb-summary.json
2023-02-16 13:05:22,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_created():275] file/dir created: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/requirements.txt
2023-02-16 13:05:22,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_created():275] file/dir created: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/conda-environment.yaml
2023-02-16 13:05:23,233 DEBUG   HandlerThread:21960 [system_info.py:_save_conda():86] Saving conda packages done
2023-02-16 13:05:23,234 INFO    HandlerThread:21960 [system_monitor.py:probe():187] Finished publishing system info
2023-02-16 13:05:23,234 DEBUG   SenderThread:21960 [sender.py:send():334] send: files
2023-02-16 13:05:23,234 INFO    SenderThread:21960 [sender.py:_save_file():1319] saving file wandb-metadata.json with policy now
2023-02-16 13:05:23,241 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: stop_status
2023-02-16 13:05:23,242 DEBUG   SenderThread:21960 [sender.py:send_request():361] send_request: stop_status
2023-02-16 13:05:23,442 DEBUG   SenderThread:21960 [sender.py:send():334] send: telemetry
2023-02-16 13:05:23,847 INFO    Thread-232:21960 [upload_job.py:push():143] Uploaded file /tmp/tmp5a584tipwandb/8010pf9j-wandb-metadata.json
2023-02-16 13:05:24,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/conda-environment.yaml
2023-02-16 13:05:24,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_created():275] file/dir created: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/output.log
2023-02-16 13:05:24,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_created():275] file/dir created: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/wandb-metadata.json
2023-02-16 13:05:26,006 INFO    Thread-229:21960 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/files/output.log
2023-02-16 13:05:26,444 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:31,445 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:36,445 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:38,241 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:05:38,241 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:05:41,446 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:43,242 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:05:46,446 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:48,242 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:05:51,449 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: status_report
2023-02-16 13:05:51,653 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:05:51,653 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:05:53,106 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:05:53,107 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:05:53,243 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:05:55,598 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:05:55,598 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:05:55,598 INFO    SenderThread:21960 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-02-16 13:05:58,243 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:00,083 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:06:00,083 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:06:03,244 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:08,245 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:09,776 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:06:09,776 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:06:13,245 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:18,246 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:21,098 DEBUG   SystemMonitor:21960 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-02-16 13:06:23,246 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:28,247 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:28,333 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:06:28,333 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:06:33,248 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:38,248 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:43,249 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:48,249 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:53,250 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:06:58,250 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:02,512 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:07:02,513 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:07:03,251 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:08,251 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:13,252 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:18,252 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:23,253 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:28,254 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:33,254 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:35,567 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: partial_history
2023-02-16 13:07:38,255 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:43,256 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:48,256 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:53,257 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:07:58,257 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:08:03,258 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:08:08,259 DEBUG   HandlerThread:21960 [handler.py:handle_request():144] handle_request: keepalive
2023-02-16 13:08:08,334 ERROR   SenderThread:21960 [internal_api.py:execute():244] 409 response executing GraphQL.
2023-02-16 13:08:08,334 ERROR   SenderThread:21960 [internal_api.py:execute():245] {"errors":[{"message":"run luigidoria/Teste de temperatura knowledge distillation Cifar100/zr31z4za was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-16 13:08:08,334 INFO    HandlerThread:21960 [handler.py:finish():841] shutting down handler
2023-02-16 13:08:08,334 INFO    WriterThread:21960 [datastore.py:close():299] close: /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/run-zr31z4za.wandb
2023-02-16 13:08:08,658 ERROR   StreamThr :21960 [internal.py:wandb_internal():175] Thread SenderThread:
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1592, in upsert_run
    response = self.gql(
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 213, in gql
    ret = self._retry_gql(
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 335, in _debounce
    self._sm.debounce()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 510, in debounce
    self._maybe_update_config(always=final)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 487, in _maybe_update_config
    self._debounce_config()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 516, in _debounce_config
    self._api.upsert_run(
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 28, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
